### ISSUE TITLE
🛠️ 커스텀 훅에서 의존성 체크에 대한 에러 처리 추가

### ISSUE THREAD

**Issue by zero0205** [boostcampwm-2024/web20-camon#204]
### 📣 수정 제목

커스텀 훅에서 의존성 체크에 대한 에러 처리 추가

### 📣 수정 작업 이유

Live.tsx의 useEffect에서 의존성 배열에 불필요한 값을 넣어서 소켓이 Consumer를 다 만들기 전에 disconnect되는 문제가 발생했다. 그러니까 useConsumer 훅이 실행되던 중에 `socket.disconnect()` 코드가 실행되며 socket이 없어서 createConsumer 이벤트가 발생하지 못했던 것이다.

이 문제의 원인을 찾을 때 각 커스텀 훅의 의존성이 없을 때 `setError`를 하지 않고, 그냥 return만 해서 문제의 원인을 찾기 어려웠다. 그렇기에 각 커스텀 훅의 의존성이 없을 때도 에러를 세팅하도록 수정하려고 한다.

### ✅ 작업 리스트

- [x] useConsumer
- [ ] useMediaControls
- [x] useProducer
- [x] useRoom
- [x] useTransport

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified useConsumer hook to set errors when dependencies are missing. This will help in identifying issues when the hook is not provided with all necessary dependencies.

You can review changes in this commit: https://github.com/lattaai13/boostcampwm-2024-web20-camon-204/commit/afdda8fc4eddc7cdffe39169056a10a1baef8bb5.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
